package com.artembilous.docugen.entity;

public enum AuditAction {
    DOCUMENT_GENERATED,
    DOCUMENT_FINALISED,
    DOCUMENT_REVERTED,
    DOCUMENT_VIEWED,

    TEMPLATE_CREATED,
    TEMPLATE_UPDATED,
    TEMPLATE_PUBLISHED,

    ORGANISATION_CREATED,
    ORGANISATION_RENAMED,

    ROLE_CREATED,
    ROLE_UPDATED,
    ROLE_DELETED,
    MEMBER_ROLES_UPDATED,

    USER_INVITED,

    API_TOKEN_GENERATED,
    API_TOKEN_DELETED,
}